import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Auth0Provider } from "@auth0/auth0-react";
import { AxiosClientProvider } from "@/axios/AxiosClientProvider";
import AppHeader from "@/components/organisms/AppHeader";
import AppFooter from "@/components/organisms/AppFooter";
import styles from "@/styles/Home.module.css";
import CurrentUserProvider from "@/contexts/CurrentUserProvider";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const redirectUri = `${process.env.NEXT_PUBLIC_BASE_URL}/mypage`;
  const redirectUriDev = "http://localhost:3000/mypage";
  return (
    <>
      <Head>
        <title>ミーティング調整ツール</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth0Provider
        domain={process.env.NEXT_PUBLIC_AUTH0_DOMAIN!}
        clientId={process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID!}
        authorizationParams={{
          redirect_uri: redirectUri,
          // redirect_uri: redirectUriDev,
          audience: process.env.NEXT_PUBLIC_AUTH0_AUDIENCE!,
        }}
      >
        <AxiosClientProvider>
          <CurrentUserProvider>
            <LocalizationProvider dateAdapter={AdapterDayjs}>
              <>
                <AppHeader />
                <main className={styles.main}>
                  <Component {...pageProps} />
                </main>
                {/* <AppFooter /> */}
              </>
            </LocalizationProvider>
          </CurrentUserProvider>
        </AxiosClientProvider>
      </Auth0Provider>
    </>
  );
}
