import Head from "next/head";
import LoginOrSingupButton from "@/components/organisms/LoginOrSignupButton";
import { Link } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Preview Meeting App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/guest" sx={{ mb: 3 }}>
        ゲストログイン
      </Link>
      <LoginOrSingupButton />
    </>
  );
}
